image: 
  repository: 9mine/9mine-azure-cloud-fs
  tag: "main"
  pullPolicy: Always

initContainerImage:
  repository: 9mine/execfuse-jinja2
  tag: "master"
  pullPolicy: Always

securityContext: 
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN

service:
  type: ClusterIP
  port: 3900
  
ClusterIPRange:
    from: 3901
    to: 3920

description: "azurecloudfs"

fs: |
    {% include './common.j2' %}
    fs:
      # root
      "/":
        readdir: 
          sh: ls /accounts
        getattr:
          sh: *dir 
          # /<id>
        "/[0-9]+":
          name: id
          readdir: 
            list: 
            - vm
          getattr: 
              sh: *dir
          # /<id>/.init.lua
          "/.init.lua":
            getattr:
              sh: *file
            read_file: 
              sh: |
                cat <<EOF
                   local function set_texture(entry, entity)
                       local prefix = init_path:match("/$") and init_path:sub(1, -2) or init_path
                       if not prefix then
                           return
                       end
                       local azure_textures_directory = "9mine-azure-cloud-fs"
                       local texture_prefix = "9mine-azure-cloud-fs"
                       if entry.entry_string == prefix .. "/vm" then
                           local tx_name = texture_prefix .. "-vm.png"
                           texture.download(
                               "https://www.clipartmax.com/png/middle/18-189604_microsoft-azure-icon-logo-vector-microsoft-azure-logo-vector.png",
                               true, tx_name, azure_textures_directory)
                           entity:set_properties({
                               visual = "sprite",
                               textures = {tx_name}
                           })
                       end
                       if entry.entry_string == prefix .. "/vm/list" then
                           local tx_name = texture_prefix .. "-vm-list.png"
                           texture.download("https://theautomationguy.files.wordpress.com/2019/08/img_1342.png?w=641&h=619&crop=1", true,
                               tx_name, azure_textures_directory)
                           entity:set_properties({
                               visual = "sprite",
                               textures = {tx_name}
                           })
                       end
                       if entry.platform_string == prefix .. "/vm/list" then
                           local tx_name = texture_prefix .. "-vm-instance.png"
                           texture.download(
                               "https://www.pikpng.com/pngl/m/230-2302946_azure-service-fabric-icon-png-download-azure-virtual.png",
                               true, tx_name, azure_textures_directory)
                           entity:set_properties({
                               visual = "sprite",
                               textures = {tx_name}
                           })
                       end

                       if entry.platform_string:match(string.gsub(prefix .. "/vm/list", "%-", "%%%-") .. "/[%d%a%p]+") then
                           local tx_name = texture_prefix .. "-vm-conf.png"
                           texture.download("https://static.thenounproject.com/png/1274728-200.png", true, tx_name,
                               azure_textures_directory)
                           entity:set_properties({
                               visual = "sprite",
                               textures = {tx_name}
                           })
                       end
                   end
                   register.add_texture_handler(init_path .. "9mine-azure-cloud-fs", set_texture)
           
                EOF
                
          # /<id>/vm
          "/vm":
            readdir:
              list: 
              - list
            getattr:
              sh: *dir
              # /<id>/vm/list
            "/list":
              cache: 360
              readdir:
                sh: export AZURE_CONFIG_DIR=/accounts/$id/credentials && az vm list | jq -r '.[].name'
              getattr:
                sh: *dir 
              # /<id>/vm/list/<instance>
              "/[a-z0-9_-]+":
                name: instancename
                getattr: 
                  sh: *dir 
                readdir: 
                  sh: export AZURE_CONFIG_DIR=/accounts/$id/credentials && az vm list | jq -r ".[] | select (.name==\"$instancename\")" | jq -r "keys[]"
                # /<id>/vm/list/<instance>/<parameter>
                "/[a-zA-Z0-9_-]+":
                  name: parameter
                  getattr:
                    sh: *file
                  read_file:
                    sh: export AZURE_CONFIG_DIR=/accounts/$id/credentials && az vm list | jq -r ".[] | select (.name==\"$instancename\") .\"$parameter\""



profile: |
    echo --- start of profile loading ---
    load file2chan
    load std
    ndb/cs
    for host_var in `{ os env } { '{'$host_var'}' }
    
    dir = $EXPORT_PATH
    port = $NINEP_PUBLIC_PORT
    echo $NINEP_PUBLIC_HOST > /dev/sysname 
    test -d /mnt/registry || mkdir -p /mnt/registry
    mount -A tcp!registry!registry /mnt/registry
    AZURE_DIR = /tmp/azure/cmd
    test -d $AZURE_DIR || mkdir -p $AZURE_DIR
    load mpexpr
    fs_port = ${expr $NINEP_PUBLIC_PORT 1 +}
    file2chan $AZURE_DIR^/azure {} {
        load mpexpr
        var=${expr 10 rand}
        echo new id is $var
        echo hostname is `{os hostname}
        (app_id password tenant) = `{echo ${rget data}} 
        `{os /bin/bash -c 'mkdir -p /accounts/'^$var}
        `{os /bin/bash -c 'export AZURE_CONFIG_DIR=/accounts/'^$var^'/credentials && az login --service-principal -u '^$app_id^' -p '^$password^' --tenant '^$tenant^''}
        grid/reglisten -A -r description 'user id is '^$var tcp!*!^$fs_port { export $dir^/^$var & } &
        fs_port=${expr $fs_port 1 +}
    }
        
    grid/reglisten -A -r description ${quote $NINEP_DESCRIPTION} 'tcp!*!'^$port { export $AZURE_DIR & }
    test -n $status && os pkill -9 emu-g
    echo --- end of profile loading ---